config/routes.rb
MyAcademy::Application.routes.draw do
  devise_for :teachers

  devise_scope :teacher do
    get "/login", to: "devise/sessions#new", as: :login
    get "/signup", to: "devise/registrations#new", as: :signup
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  get "/", to: "teachers#profile", as: :home
  get "/oai" , to: "oai#index", as: :oai
  get "/teachers/export/europass/xml", to: "export#europass_xml", as: :export_europass_xml
  get "/teachers/export/europass/pdf", to: "export#europass_pdf", as: :export_europass_pdf
  get "/teachers/export/pdf", to: "export#latex_pdf", as: :export_resume_pdf
  get "/teachers/export/md", to: "export#md", as: :export_resume_md
  get "/xslfo", to: "export#xslfo", as: :export_xslfo
  get "/search", to: "teachers#search", as: :search
  get "/profile" => "teachers#profile", as: :user_profile

  get "/linkedin/auth", to: "auth#auth", as: :auth_linkedin
  get "/linkedin/callback", to: "auth#callback", as: :linkedin_callback

  get "/:username" => "teachers#show", as: :user_profiles
  get "/ficheiros/:id/delete", to: "ficheiros#destroy", as: :ficheiro_delete
  get "/folders/:id/delete", to: "folders#destroy", as: :folder_delete

  resources :theses
  resources :thesis_supervisions
  resources :teachers
  resources :academic_degrees
  resources :academic_informations
  resources :activities
  resources :activity_types
  resources :authors
  resources :cosupervisors
  resources :courses
  resources :deliverables
  resources :editors
  resources :entities
  resources :ficheiros
  resources :folders
  resources :hobbies
  resources :institutions
  resources :managements
  resources :publication_types
  resources :publications
  resources :research_projects
  resources :roles
  resources :subjects
  resources :tags
  resources :thesis_examinations
  resources :teachers
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :activity_type
  belongs_to :teacher
end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :publication
end

app/models/cosupervisor.rb
class Cosupervisor < ActiveRecord::Base
  belongs_to :thesis_supervision
  belongs_to :teacher
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :institution
  has_many :subjects
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :publication
end

app/models/editor.rb
class Editor < ActiveRecord::Base
  belongs_to :publication
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/ficheiro.rb
class Ficheiro < ActiveRecord::Base
  belongs_to :subject
  belongs_to :folder
  has_many :file_tags
  has_attached_file :file
  has_many :tags, through: :file_tags
end

app/models/file_tag.rb
class FileTag < ActiveRecord::Base
  belongs_to :file
  belongs_to :tag
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :subject
  belongs_to :folder
  has_many :ficheiros
  has_many :folders
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
  belongs_to :teacher
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :teachers
  has_many :courses
  has_many :theses
end 

app/models/management.rb
class Management < ActiveRecord::Base
  belongs_to :role
  belongs_to :entity
  belongs_to :teacher
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :publication_type
  belongs_to :research_project
  has_many :authors
  has_many :editors
  has_many :deliverables
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :folders
  has_many :files
  belongs_to :course
  belongs_to :teacher
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :file_tags
  has_many :files, through: :file_tags
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :institution
  has_many :hobbies
  has_many :academic_informations
  has_many :subjects
  has_many :managements
  has_many :activities
  has_many :thesis_supervisions
  has_many :thesis_examinations
  has_many :research_projects
  has_many :thesis_supervisions, through: :cosupervisors
  has_many :cosupervisors
  has_many :publications

  has_attached_file :photo, :default_url => "assets/avatar.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  fuzzily_searchable :name, :email

  def sort_academic_informations
    self.academic_informations.sort_by{|ai| ai.b_date}
  end
end

app/models/thesis.rb
class Thesis < ActiveRecord::Base
  belongs_to :academic_degree
  belongs_to :institution
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_teacher!, except: [:show, :search]
  before_action :set_teacher, only: [ :show, :edit, :update, :destroy]


  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to home_path, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to home_path, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  def profile
    @teacher = Teacher.find(current_teacher.id)
  end

  def search
    search = params[:search]
    @teachers_filtered = Teacher.all.order(name: :asc)
    if !@teachers_filtered.blank?
      if !search or search==""
        @teachers_filtered
      else
        @teachers_filtered = @teachers_filtered.find_by_fuzzy_name(search) & @teachers_filtered
      end
    end
    @teachers_filtered
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      if params[:id]
        @teacher = Teacher.find(params[:id])
      else
        @teacher = Teacher.find_by(username: params[:username])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :username,:status, :phone, :birthday, :url, :bio, :registed, :institution_id, :email, :encrypted_password)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.slim
= form_for @teacher, html: {class: "form-horizontal", role: "form"} do |f|
  .form_group
    .row
      label.col-sm-3.control-label 
      .col-sm-9.m-t-10
        .m-b-10
          div Institution
          .row
            .col-sm-8
              .form-group
                  select.form-control.selectpicker name="teacher[institution_id]" data-live-search="true" class="input input-large input-light brad" style="width: 100%"
                    = Institution.all.each do |i|
                      option value="#{i.id}" #{i.name}
        .m-b-10
          div Name
          .row
            .col-sm-8
              = f.text_field :name, class: "input input-large input-light brad", style: "width: 100%", required:"true"
        .m-b-10
          div Email
          .row
            .col-sm-8
              = f.text_field :email, class: "input input-large input-light brad", style: "width: 100%", required:"true"
        .m-b-10
          div Birthday
          .row
            .col-sm-8
              = f.text_field :birthday, "data-behaviour" => 'datepicker', "data-date-format"=> "dd-mm-yyyy", class: "input form-control datepicker", style: "width: 100%"
        .m-b-10
          div Status
          .row
            .col-sm-8
              = f.text_field :status, class: "input input-large input-light brad", style: "width: 100%"
        
        .m-b-10
          div Phone
          .row
            .col-sm-8
              = f.text_field :phone, class: "input input-large input-light brad", style: "width: 100%"
        .m-b-10
          div url
          .row
            .col-sm-8
              = f.text_field :url, class: "input input-large input-light brad", style: "width: 100%"
        .m-b-10
          div Bio
          .row
            .col-sm-8
              = f.text_area :bio, class: "input input-large input-light brad", style: "width: 100%"

        .m-b-10
          div Password
          .row
            .col-sm-8
              = f.password_field :password, :class => "input input-large input-light brad", :placeholder => "Password", required: "true",style: "width: 100%"
        .m-b-10
          div Confirm Password
          .row
            .col-sm-8
              = f.password_field :password_confirmation, :class => "input input-large input-light brad", :placeholder => "Confirm Password", required: "true", style: "width: 100%"
      #custom_fields
      .col-sm-3
      .col-sm-9
        button.btn.btn-lg.btn-primary Save

app/views/teachers/edit.slim
body.bg-gray-light
  = render "teachers/shared/navbar"
  = render "teachers/shared/sidebar", active: "my_edit"
  #container.main-content.p-30.tp-t-60.tp-lr-10.active
    =render "shared/errors"
    button.menu-btn.btn.btn-bordered.text-gray-alt.text-bold.top-left-corner ☰ MENU
    = render "teachers/profile/header"
    .bg-white.p-30.m-t-10.brad.b-bot-2px-gray-light.b-right-1px-gray-light
      h2.text-center.p-b-30-m-t-0.page-header Edit profile
      = render "teachers/form"

  script src="https://code.jquery.com/jquery.js"
  script src="/assets/lib/bootstrap.js"
  script src="/assets/lib/pushy.js"
  script src="/assets/lib/icheck.js"
  script src="/assets/lib/bootstrap-select.js"
  script src="/assets/lib/bootstrap-datepicker.js"
  script src="/assets/admin.js"

  javascript:
    $('.datepicker').datepicker()

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Phone</th>
      <th>Birthday</th>
      <th>Url</th>
      <th>Bio</th>
      <th>Registed</th>
      <th>Institution</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.status %></td>
        <td><%= teacher.phone %></td>
        <td><%= teacher.birthday %></td>
        <td><%= teacher.url %></td>
        <td><%= teacher.bio %></td>
        <td><%= teacher.registed %></td>
        <td><%= teacher.institution %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.encrypted_password %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/profile.slim
body.bg-gray-light
  = render "teachers/shared/navbar"
  = render "teachers/shared/sidebar", active: "profile"
  #container.main-content.p-30.tp-t-60.tp-lr-10.active
    =render "shared/errors"
    button.menu-btn.btn.btn-bordered.text-gray-alt.text-bold.top-left-corner ☰ MENU
    = render "teachers/profile/header"
    = render "teachers/profile/tabs"

  script src="https://code.jquery.com/jquery.js"
  script src="assets/lib/bootstrap.js"
  script src="assets/lib/pushy.js"
  script src="assets/lib/icheck.js"
  script src="assets/lib/bootstrap-select.js"
  script src="assets/admin.js"

app/views/teachers/profile/_header.slim
.row
  .col-sm-3.text-center
    .p-10.brad
      = link_to "/#{@teacher.username}"
        .img-circle.profile-pic style="margin:auto;background-image:url('#{@teacher.photo.url}')"
      div
        div
          .i-block
            h3.m-b-0
              = link_to @teacher.name, @teacher.url

        div
          .text-gray-alt.i-block
            span.m-t-10.d-block
              = link_to @teacher.email, "mailto:#{@teacher.email}"
  .col-sm-9
    .bg-white.p-30.brad.b-bot-2px-gray-light.b-right-1px-gray-light
      .row
        .col-sm-4
          h4 
            - if @teacher.status
              = @teacher.status
            - else
              | N/D
          p.text-gray-alt Status
          hr
          h4
            - if @teacher.phone
              = @teacher.phone
            - else
              | N/D
          p.text-gray-alt Phone
        .col-sm-4
          h4 = @teacher.institution.name
          p.text-gray-alt Instituition
          hr
          h4 
            - if @teacher.birthday
              = Time.now.utc.to_date.year - @teacher.birthday.year - (@teacher.birthday.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0)
              |  years old
            - else 
              |  Age N/D
          p.text-gray-alt
            | Born on 
            - if @teacher.birthday
              = @teacher.try(:birthday).strftime("%d.%m.%Y")
            - else
              |  N/D
        .col-sm-4
          h4 Registed
          p.text-gray-alt 
            |Last active at: 
            - if @teacher.last_sign_in_at
              = @teacher.try(:last_sign_in_at).strftime('%d.%m.%Y')
            - else
              |  Never active

app/views/teachers/profile/_informations.slim
#personal.tab-pane.active.fade.in.p-30
  h2.font-w-100
    span.text-blue Biography
  p.text-gray-alt
    = @teacher.bio
  hr
  h2.font-w-100
    span.text-blue Academic Degrees
  - @teacher.sort_academic_informations.each do |ai|
    .row
      .col-sm-2
        p.text-gray-alt
          span.label.label-info
            = ai.b_date.year
            | -
            - if ai.e_date
              = ai.e_date.year
            - else
              | current
      .col-sm-10
        p.text-gray-alt
          strong = ai.academic_degree.name
          |  in
          = " #{ai.course.name}"
          |  @
          = ai.course.institution.name
          br/
          - if !ai.description.blank?
            blockquote.text-gray-alt.prof
              = ai.description
  hr
  h2.font-w-100
    span.text-blue Hobbies
  - @teacher.hobbies.each do |hobby|
    span.label.label-success.m-10
      = hobby.activity

app/views/teachers/profile/_publications.slim
#publications.tab-pane.fade.p-30
  h2.font-w-100
    span.text-blue Publications
  -publications = @teacher.publications.sort_by &:date
  - publications.each do |pub|
    div vocab="http://schema.org/" typeof="CreativeWork"
      p.text-gray-alt
        span property="name"
          | [ #{pub.publication_type.name} ]
        strong #{pub.title}
        - Author.where(publication_id: pub.id).each do |author|
          span property="author" typeof="Person"
            | #{author.name} ,
        span property="publisher"  typeof="Organization"
          | #{pub.publisher}
        | #{pub.address}
        | #{pub.chapter}
        | #{pub.pages}
        | #{pub.volume}
        | #{pub.isbn}
        | #{pub.issn}
        | #{pub.booktitle}
        | #{pub.journal}
        | #{pub.number}
        | #{pub.howpublished}
        | #{pub.school}
        - if pub.uri
          a href="(pub.uri)" property="url"
            = pub.uri
      hr

app/views/teachers/profile/_research_projects.slim
#research.tab-pane.fade.p-30
  h2.font-w-100
    span.text-blue Research Projects
  - @teacher.research_projects.each do |r|
    p class="text-gray-alt"
      strong   #{r.name}  | 
      - if r.b_date
        = r.try(:b_date).strftime("%d.%m.%Y")
      - else
        |  N/D
      |  - 
      - if r.e_date
        = r.try(:e_date).strftime("%d.%m.%Y")
      - else
        |  N/D
      | |
      a href=(r.url)
        = r.url
      p class="text-gray-alt" #{r.description}  
      
    hr 

app/views/teachers/profile/_tabs.slim
ul.nav.nav-tabs.nav-profile.tab-size
  li.active
    a data-toggle="tab" href="#personal"
      .text-small Personal
      span.text-uppercase information
      span.text-gray-dark
        |  /
      span.small.text-gray-dark hobbies
  li
    a data-toggle="tab" href="#research"
      .text-small Research
      span.text-uppercase projects
      span.text-gray-dark
        |  /
      span.small.text-gray-dark investigation
  li
    a data-toggle="tab" href="#publications"
      .text-small Documents
      span.text-uppercase Publications
  li
    a data-toggle="tab" href="#thesup"
      .text-small Thesis
      span.text-uppercase Supervisions
  li
    a data-toggle="tab" href="#thexam"
      .text-small Thesis
      span.text-uppercase Examinations
  li
    a data-toggle="tab" href="#conf"
      .text-small Conferences
      span.text-uppercase Organization
      span.text-gray-dark
        |  /
      span.small.text-gray-dark Member
  li
    a data-toggle="tab" href="#teaching"
      .text-small Professor
      span.text-uppercase Teaching

.bg-white.b-1px-gray-light.b-top-none.brad-bottom.brad-tr.b-bot-2px-gray-light
  .tab-content.profilecontainer

    = render "teachers/profile/informations"
    = render "teachers/profile/research_projects"
    = render "teachers/profile/publications"
    = render "teachers/profile/thesis_supervisions"
    = render "teachers/profile/thesis_examinations"
    = render "teachers/profile/teaching"

 

app/views/teachers/profile/_teaching.slim
#teaching.tab-pane.fade.in.p-30
  h2.font-w-100
    span.text-blue Teaching

  - @teacher.subjects.each do |s|
    - @folder = s.folders.where(folder_id: 0).first
    = link_to @folder
      .row 
        .col-sm-2
          p.text-gray-alt
            span.label.label-info
              = s.academic_year
        .col-sm-10
          p.text-gray-alt
            strong = " #{s.name}"
            | :  
            = s.course.name
            br
            = s.course.institution.name
            br/
            - if !s.description.blank?
              blockquote.text-gray-alt.prof
                = s.description

app/views/teachers/profile/_thesis_examinations.slim
#thexam.tab-pane.fade.p-30
  h2.font-w-100
    span.text-blue Thesis Examinations
  - @teacher.thesis_examinations.each do |thesis|
    p.text-gray-alt
      | [ #{thesis.date.strftime("%Y.%m.%d")} ]  
      strong 
        | [ #{thesis.thesis.academic_degree.name } ] #{thesis.thesis.title}    
      = link_to thesis.thesis.student , search_path(search: thesis.thesis.student)
      |  @ #{thesis.thesis.institution.name  } 
      a href=(thesis.thesis.url)
        = thesis.thesis.url
      p #{thesis.description } 
    hr 

app/views/teachers/profile/_thesis_supervisions.slim
#thesup.tab-pane.fade.p-30
  h2.font-w-100
    span.text-blue Thesis Supervisions
  - ThesisSupervision.where(teacher_id: @teacher.id).each do |thesis|
    p.text-gray-alt
      strong
        | [ #{thesis.thesis.academic_degree.name } ]  #{thesis.thesis.title}   
      = link_to thesis.thesis.student , search_path(search: thesis.thesis.student) 
      | @ #{thesis.thesis.institution.name }  
      a href=(thesis.thesis.url)
        = thesis.thesis.url
    p #{thesis.description }  
    hr 

app/views/teachers/search.slim
body.bg-gray-light
  = render "teachers/shared/navbar"
  = render "teachers/shared/sidebar", active: "search"
  #container.main-content.p-30.tp-t-60.tp-lr-10.active
    =render "shared/errors"
    button.menu-btn.btn.btn-bordered.text-gray-alt.text-bold.top-left-corner ☰ MENU
    .p-30
      h1.text-center.font-w-100
       | Search related users
      hr
      .text-center
        = form_tag search_path, method: :get do
          = text_field_tag 'Search', "" , value: params[:search], class:"input input-light input-large brad valign-top m-r-10 m-l-10 search-box",placeholder:"Search...", type:"text", style:"width: 50%"
          button.btn.btn-info type="submit" Procurar

      hr 

      = render "teachers/search/search_results"

  script src="https://code.jquery.com/jquery.js"
  script src="/assets/lib/bootstrap.js"
  script src="/assets/lib/pushy.js"
  script src="/assets/lib/icheck.js"
  script src="/assets/lib/bootstrap-select.js"
  script src="/assets/lib/bootstrap-datepicker.js"
  script src="/assets/admin.js"

app/views/teachers/show.slim
body.bg-gray-light
  = render "teachers/shared/navbar"
  = render "teachers/shared/sidebar", active: "profile"
  #container.main-content.p-30.tp-t-60.tp-lr-10.active
    =render "shared/errors"
    button.menu-btn.btn.btn-bordered.text-gray-alt.text-bold.top-left-corner ☰ MENU
    = render "teachers/profile/header"
    = render "teachers/profile/tabs"

  script src="https://code.jquery.com/jquery.js"
  script src="assets/lib/bootstrap.js"
  script src="assets/lib/pushy.js"
  script src="assets/lib/icheck.js"
  script src="assets/lib/bootstrap-select.js"
  script src="assets/admin.js"

app/views/teachers/user_profile.slim
body.bg-gray-light
  = render "teachers/shared/navbar"
  = render "teachers/shared/sidebar", active: "profile"
  #container.main-content.p-30.tp-t-60.tp-lr-10.active
    =render "shared/errors"
    button.menu-btn.btn.btn-bordered.text-gray-alt.text-bold.top-left-corner ☰ MENU
    = render "teachers/profile/header"
    = render "teachers/profile/tabs"

  script src="https://code.jquery.com/jquery.js"
  script src="assets/lib/bootstrap.js"
  script src="assets/lib/pushy.js"
  script src="assets/lib/icheck.js"
  script src="assets/lib/bootstrap-select.js"
  script src="assets/admin.js"