config/routes.rb
MyAcademy::Application.routes.draw do
  devise_for :teachers

  devise_scope :teacher do
    get "/login", to: "devise/sessions#new", as: :login
    get "/signup", to: "devise/registrations#new", as: :signup
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  get "/", to: "teachers#profile", as: :home
  get "/oai" , to: "oai#index", as: :oai
  get "/teachers/export/europass/xml", to: "export#europass_xml", as: :export_europass_xml
  get "/teachers/export/europass/pdf", to: "export#europass_pdf", as: :export_europass_pdf
  get "/teachers/export/pdf", to: "export#latex_pdf", as: :export_resume_pdf
  get "/teachers/export/md", to: "export#md", as: :export_resume_md
  get "/xslfo", to: "export#xslfo", as: :export_xslfo
  get "/search", to: "teachers#search", as: :search
  get "/profile" => "teachers#profile", as: :user_profile

  get "/linkedin/auth", to: "auth#auth", as: :auth_linkedin
  get "/linkedin/callback", to: "auth#callback", as: :linkedin_callback

  get "/:username" => "teachers#show", as: :user_profiles
  get "/ficheiros/:id/delete", to: "ficheiros#destroy", as: :ficheiro_delete
  get "/folders/:id/delete", to: "folders#destroy", as: :folder_delete

  resources :theses
  resources :thesis_supervisions
  resources :teachers
  resources :academic_degrees
  resources :academic_informations
  resources :activities
  resources :activity_types
  resources :authors
  resources :cosupervisors
  resources :courses
  resources :deliverables
  resources :editors
  resources :entities
  resources :ficheiros
  resources :folders
  resources :hobbies
  resources :institutions
  resources :managements
  resources :publication_types
  resources :publications
  resources :research_projects
  resources :roles
  resources :subjects
  resources :tags
  resources :thesis_examinations
  resources :teachers
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :activity_type
  belongs_to :teacher
end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :publication
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :institution
  has_many :subjects
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :publication
end

app/models/editor.rb
class Editor < ActiveRecord::Base
  belongs_to :publication
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/ficheiro.rb
class Ficheiro < ActiveRecord::Base
  belongs_to :subject
  belongs_to :folder
  has_many :file_tags
  has_attached_file :file
  has_many :tags, through: :file_tags
end

app/models/file_tag.rb
class FileTag < ActiveRecord::Base
  belongs_to :file
  belongs_to :tag
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :subject
  belongs_to :folder
  has_many :ficheiros
  has_many :folders
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
  belongs_to :teacher
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :teachers
  has_many :courses
  has_many :theses
end 

app/models/management.rb
class Management < ActiveRecord::Base
  belongs_to :role
  belongs_to :entity
  belongs_to :teacher
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :publication_type
  belongs_to :research_project
  has_many :authors
  has_many :editors
  has_many :deliverables
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :folders
  has_many :files
  belongs_to :course
  belongs_to :teacher
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :file_tags
  has_many :files, through: :file_tags
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :institution
  has_many :hobbies
  has_many :academic_informations
  has_many :subjects
  has_many :managements
  has_many :activities
  has_many :thesis_supervisions
  has_many :thesis_examinations
  has_many :research_projects
  has_many :thesis_supervisions, through: :cosupervisors
  has_many :cosupervisors
  has_many :publications

  has_attached_file :photo, :default_url => "assets/avatar.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  fuzzily_searchable :name, :email

  def sort_academic_informations
    self.academic_informations.sort_by{|ai| ai.b_date}
  end
end

app/models/thesis.rb
class Thesis < ActiveRecord::Base
  belongs_to :academic_degree
  belongs_to :institution
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/controllers/publication_types_controller.rb
class PublicationTypesController < ApplicationController
  before_action :set_publication_type, only: [:show, :edit, :update, :destroy]

  # GET /publication_types
  # GET /publication_types.json
  def index
    @publication_types = PublicationType.all
  end

  # GET /publication_types/1
  # GET /publication_types/1.json
  def show
  end

  # GET /publication_types/new
  def new
    @publication_type = PublicationType.new
  end

  # GET /publication_types/1/edit
  def edit
  end

  # POST /publication_types
  # POST /publication_types.json
  def create
    @publication_type = PublicationType.new(publication_type_params)

    respond_to do |format|
      if @publication_type.save
        format.html { redirect_to @publication_type, notice: 'Publication type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @publication_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @publication_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publication_types/1
  # PATCH/PUT /publication_types/1.json
  def update
    respond_to do |format|
      if @publication_type.update(publication_type_params)
        format.html { redirect_to @publication_type, notice: 'Publication type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @publication_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publication_types/1
  # DELETE /publication_types/1.json
  def destroy
    @publication_type.destroy
    respond_to do |format|
      format.html { redirect_to publication_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication_type
      @publication_type = PublicationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_type_params
      params.require(:publication_type).permit(:name)
    end
end

app/helpers/publication_types_helper.rb
module PublicationTypesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/publication_types/_form.html.erb
<%= form_for(@publication_type) do |f| %>
  <% if @publication_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication_type.errors.count, "error") %> prohibited this publication_type from being saved:</h2>

      <ul>
      <% @publication_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publication_types/edit.html.erb
<h1>Editing publication_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication_type %> |
<%= link_to 'Back', publication_types_path %>

app/views/publication_types/index.html.erb
<h1>Listing publication_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @publication_types.each do |publication_type| %>
      <tr>
        <td><%= publication_type.name %></td>
        <td><%= link_to 'Show', publication_type %></td>
        <td><%= link_to 'Edit', edit_publication_type_path(publication_type) %></td>
        <td><%= link_to 'Destroy', publication_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication type', new_publication_type_path %>

app/views/publication_types/new.html.erb
<h1>New publication_type</h1>

<%= render 'form' %>

<%= link_to 'Back', publication_types_path %>

app/views/publication_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publication_type.name %>
</p>

<%= link_to 'Edit', edit_publication_type_path(@publication_type) %> |
<%= link_to 'Back', publication_types_path %>