config/routes.rb
MyAcademy::Application.routes.draw do
  devise_for :teachers

  devise_scope :teacher do
    get "/login", to: "devise/sessions#new", as: :login
    get "/signup", to: "devise/registrations#new", as: :signup
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  get "/", to: "teachers#profile", as: :home
  get "/oai" , to: "oai#index", as: :oai
  get "/teachers/export/europass/xml", to: "export#europass_xml", as: :export_europass_xml
  get "/teachers/export/europass/pdf", to: "export#europass_pdf", as: :export_europass_pdf
  get "/teachers/export/pdf", to: "export#latex_pdf", as: :export_resume_pdf
  get "/teachers/export/md", to: "export#md", as: :export_resume_md
  get "/xslfo", to: "export#xslfo", as: :export_xslfo
  get "/search", to: "teachers#search", as: :search
  get "/profile" => "teachers#profile", as: :user_profile

  get "/linkedin/auth", to: "auth#auth", as: :auth_linkedin
  get "/linkedin/callback", to: "auth#callback", as: :linkedin_callback

  get "/:username" => "teachers#show", as: :user_profiles
  get "/ficheiros/:id/delete", to: "ficheiros#destroy", as: :ficheiro_delete
  get "/folders/:id/delete", to: "folders#destroy", as: :folder_delete

  resources :theses
  resources :thesis_supervisions
  resources :teachers
  resources :academic_degrees
  resources :academic_informations
  resources :activities
  resources :activity_types
  resources :authors
  resources :cosupervisors
  resources :courses
  resources :deliverables
  resources :editors
  resources :entities
  resources :ficheiros
  resources :folders
  resources :hobbies
  resources :institutions
  resources :managements
  resources :publication_types
  resources :publications
  resources :research_projects
  resources :roles
  resources :subjects
  resources :tags
  resources :thesis_examinations
  resources :teachers
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :activity_type
  belongs_to :teacher
end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :publication
end

app/models/cosupervisor.rb
class Cosupervisor < ActiveRecord::Base
  belongs_to :thesis_supervision
  belongs_to :teacher
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :institution
  has_many :subjects
end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  belongs_to :publication
end

app/models/editor.rb
class Editor < ActiveRecord::Base
  belongs_to :publication
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/ficheiro.rb
class Ficheiro < ActiveRecord::Base
  belongs_to :subject
  belongs_to :folder
  has_many :file_tags
  has_attached_file :file
  has_many :tags, through: :file_tags
end

app/models/file_tag.rb
class FileTag < ActiveRecord::Base
  belongs_to :file
  belongs_to :tag
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :subject
  belongs_to :folder
  has_many :ficheiros
  has_many :folders
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
  belongs_to :teacher
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :teachers
  has_many :courses
  has_many :theses
end 

app/models/management.rb
class Management < ActiveRecord::Base
  belongs_to :role
  belongs_to :entity
  belongs_to :teacher
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :publication_type
  belongs_to :research_project
  has_many :authors
  has_many :editors
  has_many :deliverables
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :folders
  has_many :files
  belongs_to :course
  belongs_to :teacher
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :file_tags
  has_many :files, through: :file_tags
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :institution
  has_many :hobbies
  has_many :academic_informations
  has_many :subjects
  has_many :managements
  has_many :activities
  has_many :thesis_supervisions
  has_many :thesis_examinations
  has_many :research_projects
  has_many :thesis_supervisions, through: :cosupervisors
  has_many :cosupervisors
  has_many :publications

  has_attached_file :photo, :default_url => "assets/avatar.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  fuzzily_searchable :name, :email

  def sort_academic_informations
    self.academic_informations.sort_by{|ai| ai.b_date}
  end
end

app/models/thesis.rb
class Thesis < ActiveRecord::Base
  belongs_to :academic_degree
  belongs_to :institution
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :set_management, only: [:show, :edit, :update, :destroy]

  # GET /managements
  # GET /managements.json
  def index
    @managements = Management.all
  end

  # GET /managements/1
  # GET /managements/1.json
  def show
  end

  # GET /managements/new
  def new
    @management = Management.new
  end

  # GET /managements/1/edit
  def edit
  end

  # POST /managements
  # POST /managements.json
  def create
    @management = Management.new(management_params)

    respond_to do |format|
      if @management.save
        format.html { redirect_to @management, notice: 'Management was successfully created.' }
        format.json { render action: 'show', status: :created, location: @management }
      else
        format.html { render action: 'new' }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managements/1
  # PATCH/PUT /managements/1.json
  def update
    respond_to do |format|
      if @management.update(management_params)
        format.html { redirect_to @management, notice: 'Management was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managements/1
  # DELETE /managements/1.json
  def destroy
    @management.destroy
    respond_to do |format|
      format.html { redirect_to managements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_management
      @management = Management.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def management_params
      params.require(:management).permit(:b_date, :e_date, :description, :teacher_id, :role_id, :entity_id)
    end
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/managements/_form.html.erb
<%= form_for(@management) do |f| %>
  <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% @management.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :b_date %><br>
    <%= f.datetime_select :b_date %>
  </div>
  <div class="field">
    <%= f.label :e_date %><br>
    <%= f.datetime_select :e_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.collection_select :teacher_id, Teacher.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.collection_select :role_id, Role.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :entity %><br>
    <%= f.collection_select :entity_id, Entity.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managements/edit.html.erb
<h1>Editing management</h1>

<%= render 'form' %>

<%= link_to 'Show', @management %> |
<%= link_to 'Back', managements_path %>

app/views/managements/index.html.erb
<h1>Listing managements</h1>

<table>
  <thead>
    <tr>
      <th>B date</th>
      <th>E date</th>
      <th>Description</th>
      <th>Teacher</th>
      <th>Role</th>
      <th>Entity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @managements.each do |management| %>
      <tr>
        <td><%= management.b_date %></td>
        <td><%= management.e_date %></td>
        <td><%= management.description %></td>
        <td><%= management.teacher %></td>
        <td><%= management.role %></td>
        <td><%= management.entity %></td>
        <td><%= link_to 'Show', management %></td>
        <td><%= link_to 'Edit', edit_management_path(management) %></td>
        <td><%= link_to 'Destroy', management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Management', new_management_path %>

app/views/managements/new.html.erb
<h1>New management</h1>

<%= render 'form' %>

<%= link_to 'Back', managements_path %>

app/views/managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>B date:</strong>
  <%= @management.b_date %>
</p>

<p>
  <strong>E date:</strong>
  <%= @management.e_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @management.description %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @management.teacher %>
</p>

<p>
  <strong>Role:</strong>
  <%= @management.role %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @management.entity %>
</p>

<%= link_to 'Edit', edit_management_path(@management) %> |
<%= link_to 'Back', managements_path %>